---
driver_plugin: vagrant
driver_config:
  customize:
    memory: 1024
    cpuexecutioncap: 100
    vrde: 'on'
    vrdeport: 5999
    vrdeauthtype: 'external'

platforms:
- name: zentoo
  driver_config:
    box: zentoo-amd64-base
    box_url: http://mirror.zenops.net/zentoo/amd64/zentoo-amd64-base.box
- name: zentoo-next
  driver_config:
    box: zentoo-next-amd64-base
    box_url: http://mirror.zenops.net/zentoo-next/amd64/zentoo-next-amd64-base.box
- name: debian-7.1.0
  driver_config:
    box: debian-7.1.0-amd64-base
    box_url: http://mirror.zenops.net/debian/amd64/debian-7.1.0-amd64-base.box
- name: ubuntu-12.04.3
  driver_config:
    box: ubuntu-12.04.3-amd64-base
    box_url: http://mirror.zenops.net/ubuntu/amd64/ubuntu-12.04.3-amd64-base.box

suites:
- name: base
  run_list:
  - role[base]
