generic:
  interval: 300

  eventmachine:
    threadpool_size: <%= node[:ganymed][:threadpool_size] %>

  collector:
    load_paths:
      - /usr/lib/ganymed/collectors

  collectors:
    network:
      exclude:
        - ^lo$
        - ^sit
    disk:
      exclude:
        - ^dev$
        - ^dev-shm$
        - rc-init-d$
        - ^run$
        - ^sys-fs-cgroup$
        - ^var-tmp-metro
        - ^usr-portage
    iostat:
      skip_numbered: true
      exclude: []
