# GitLab user. git by default
user: git

# Url to gitlab instance. Used for api calls. Should be ends with slash.
gitlab_url: "http://localhost/"

http_settings:
#  user: someone
#  password: somepass
  self_signed_cert: false

# Repositories path
repos_path: "/var/lib/git/repositories"

# File used as authorized_keys for gitlab user
auth_file: "/var/lib/git/.ssh/authorized_keys"
