# GitLab user. git by default
user: git

# Url to gitlab instance. Used for api calls. Should be ends with slash.
gitlab_url: "https://<%= node[:gitlab][:host] %>/"

http_settings:
  self_signed_cert: true

# Repositories path
repos_path: "<%= @homedir %>/repositories"

# File used as authorized_keys for gitlab user
auth_file: "<%= @homedir %>/.ssh/authorized_keys"
